version: "3.7"

services:
    backend-laravel:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./docker-files/backend/
            dockerfile: Dockerfile
        restart: on-failure
        env_file: .env
        container_name: backend
        image: backend/${PROJECTNAME}
        volumes:
          - ./projects/backend-laravel:/app-backend
        ports: 
            - 9000:9000

    frontend-react:
        container_name: frontend
        build: 
            context: ./docker-files/frontend/
            dockerfile: Dockerfile
        volumes:
            - './projects/frontend-react:/app-frontend'
            - '/app/node_modules'
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
        
    db:
        image: mysql:5.6
        container_name: database-todo
        restart: on-failure
        env_file: .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./database-mysql:/docker-entrypoint-initdb.d
        ports:
            - 33069:3306

    nginx:
        image: nginx:1.15-alpine
        restart: on-failure
        env_file: .env
        container_name: laravel-react-nginx
        working_dir: /
        ports:
            - "80:80"
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST_FRONTEND}
        volumes:
            - ./projects/backend-laravel/:/app-backend
            - ./projects/frontend-react/:/app-frontend
            - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf